/**
 * Barcode decoder regression test (H30 — mobile camera scanning was dead).
 *
 * Root cause: MobileCameraScanner decoded camera frames with `jsqr`, which is a
 * QR-only library (its own README: "A pure javascript QR code reading library").
 * Product barcodes in this system are 1D — EAN-13 (generated by
 * utils/barcodeGenerator.ts) or Code 128 (printed on labels/receipts) — so a
 * QR-only decoder can never fire `onScan` for them. The camera preview opened,
 * the laser beam animated, and nothing was ever recognized.
 *
 * This test renders real 1D barcodes with the app's own generator and decodes
 * them with the same decoder the scanner now uses, proving the fix end-to-end
 * without a device.
 *
 * Run: node scripts/test_barcode_decoder.mjs
 */
import { createCanvas } from 'canvas';
import { renderBarcodeToCanvas } from '../src/utils/barcodeGenerator.ts';
import {
  MultiFormatReader,
  BarcodeFormat,
  DecodeHintType,
  RGBLuminanceSource,
  BinaryBitmap,
  HybridBinarizer,
} from '@zxing/library';
import jsQR from 'jsqr';
import QRCode from 'qrcode';

// Mirror the decoder set wired in MobileCameraScanner.ts.
const DECODE_FORMATS = [
  BarcodeFormat.EAN_13,
  BarcodeFormat.EAN_8,
  BarcodeFormat.UPC_A,
  BarcodeFormat.UPC_E,
  BarcodeFormat.CODE_128,
  BarcodeFormat.CODE_39,
  BarcodeFormat.QR_CODE,
];

function decodeWithZxing(canvas, formats) {
  const ctx = canvas.getContext('2d');
  const { width, height } = canvas;
  const { data } = ctx.getImageData(0, 0, width, height);
  // data is RGBA; collapse to greyscale exactly like the library's own
  // HTMLCanvasElementLuminanceSource (0.299R + 0.587G + 0.114B) so the test
  // exercises the same bytes the scanner will produce in the browser.
  const luminances = new Uint8ClampedArray(width * height);
  for (let i = 0, j = 0; i < data.length; i += 4, j++) {
    luminances[j] = (306 * data[i] + 601 * data[i + 1] + 117 * data[i + 2] + 0x200) >> 10;
  }
  const luminance = new RGBLuminanceSource(luminances, width, height);
  const bitmap = new BinaryBitmap(new HybridBinarizer(luminance));
  const reader = new MultiFormatReader();
  const hints = new Map();
  hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
  hints.set(DecodeHintType.TRY_HARDER, true);
  reader.setHints(hints);
  try {
    return reader.decodeWithState(bitmap);
  } catch {
    // NotFoundException is the normal "no code in frame" result.
    return null;
  }
}

let failures = 0;
let completed = 0;
const TOTAL = 4;

function check(name, fn) {
  try {
    fn();
    console.log(`[PASS] ${name}`);
  } catch (err) {
    failures++;
    console.error(`[FAIL] ${name} — ${err && err.message ? err.message : err}`);
  } finally {
    completed++;
    if (completed === TOTAL) done();
  }
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

// The renderer draws black bars on white; a uniform image means the encoder
// rejected the input (it then paints "Code-barres invalide" in red).
function assertRendered(canvas, label) {
  const ctx = canvas.getContext('2d');
  const { width, height } = canvas;
  const { data } = ctx.getImageData(0, 0, width, height);
  let dark = 0;
  for (let i = 0; i < data.length; i += 4) if (data[i] < 128) dark++;
  const total = data.length / 4;
  if (dark === 0 || dark === total) {
    throw new Error(`${label}: render is uniform (${dark}/${total} dark px) — encoder rejected the code`);
  }
}

// 1. EAN-13 round-trip: render -> decode
{
  // Valid EAN-13: payload 613000000001 has checksum 5 by the app's own rule.
  const code = '6130000000015';
  // EAN-13 is 95 modules wide; keep >= 2px per module for reliable decoding.
  const canvas = createCanvas(380, 200);
  renderBarcodeToCanvas(canvas, code, 'ean13', { width: 380, height: 200, displayValue: false });
  assertRendered(canvas, 'EAN-13');
  const result = decodeWithZxing(canvas, DECODE_FORMATS);
  check('EAN-13 round-trip decode', () => {
    assert(result, 'decoder returned no result');
    assert(result.getText() === code, `expected ${code}, got ${result && result.getText()}`);
  });
}

// 2. Code 128 round-trip with a realistic product SKU payload
{
  const code = 'MOBI-SKU-0042';
  const canvas = createCanvas(520, 200);
  renderBarcodeToCanvas(canvas, code, 'code128', { width: 520, height: 200, displayValue: false });
  assertRendered(canvas, 'Code 128');
  const result = decodeWithZxing(canvas, DECODE_FORMATS);
  check('Code 128 round-trip decode', () => {
    assert(result, 'decoder returned no result');
    assert(result.getText() === code, `expected ${code}, got ${result && result.getText()}`);
  });
}

// 3. jsQR (the previous decoder) must NOT decode a 1D EAN-13 barcode —
//    the regression guard for the root cause.
{
  const code = '6130000000015';
  const canvas = createCanvas(380, 200);
  renderBarcodeToCanvas(canvas, code, 'ean13', { width: 380, height: 200, displayValue: false });
  assertRendered(canvas, 'EAN-13 (jsQR guard)');
  const ctx = canvas.getContext('2d');
  const { width, height } = canvas;
  const { data } = ctx.getImageData(0, 0, width, height);
  let qrResult = null;
  try {
    qrResult = jsQR(data, width, height, { inversionAttempts: 'attemptBoth' });
  } catch {
    qrResult = null;
  }
  const text = qrResult && qrResult.data ? qrResult.data : null;
  check('jsQR cannot decode 1D EAN-13 (root cause guard)', () => {
    assert(!text, `jsQR unexpectedly decoded a 1D barcode: ${text}`);
  });
}

// 4. QR code still decodes through the same path (no pairing regression)
{
  const canvas = createCanvas(320, 320);
  const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 320, 320);
  QRCode.toCanvas(canvas, JSON.stringify({ url: 'libsql://x.example.turso.io', token: 't' }), (err) => {
    if (err) {
      console.error('[FAIL] QR code still decodes via zxing — render failed');
      failures++;
      completed++;
      return;
    }
    const result = decodeWithZxing(canvas, DECODE_FORMATS);
    check('QR code still decodes via zxing', () => {
      assert(result, 'decoder returned no result');
      assert(result.getText().includes('libsql://'), 'QR payload lost');
    });
  });
}

function done() {
  if (failures > 0) {
    console.error(`\n${failures} barcode decoder test(s) FAILED`);
    process.exit(1);
  }
  console.log('\nAll barcode decoder tests passed');
}
